# Generated by Django 5.1.7 on 2025-04-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per hour', max_digits=10, null=True),
        ),
    ]
